# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - collab-app-pfe010

on:
  push:
    branches:
      - olivier
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://pfe010.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_722849d766fc42dcaa988ba5c8a4ca4f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e5de34bb9f004adca80a245edf60fd81 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: pfe010.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_722849d766fc42dcaa988ba5c8a4ca4f }}/collab-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'collab-app-pfe010'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_405d2b7ae0cc4e19a7ca94737e0c32c1 }}
        images: 'pfe010.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_722849d766fc42dcaa988ba5c8a4ca4f }}/collab-app:${{ github.sha }}'